#!/bin/bash
set -e
git pull
source venv/bin/activate
pip install -r requirements.txt
python manage.py collectstatic --noinput
python manage.py makemigrations --dry-run --check
python manage.py migrate --noinput
deactivate
npm ci --dev
./node_modules/.bin/parcel build bundles-src/index.js --dist-dir bundles --public-url="./"
systemctl restart starburger
systemctl reload nginx

curl --request POST \
     --url https://api.rollbar.com/api/1/deploy \
     --header "X-Rollbar-Access-Token: ${ROLLBAR_TOKEN}" \
     --header 'accept: application/json' \
     --header 'content-type: application/json' \
     --data '
{
  "environment": "development",
  "revision": "$(git rev-parse HEAD)"
}
'


echo "Deploy succesfull"
