# Generated by Django 5.2.7 on 2025-10-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0002_remove_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=450, verbose_name='Коментарий'),
        ),
    ]
