# Generated by Django 5.2.7 on 2025-10-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='название')),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
    ]
